### ISSUE TITLE
Force close happen when running

### ISSUE THREAD

**Issue by tuanvv90** [tuanvv90/AcadProject#1]
[Reproduce route]
1) Open Autocad
2) Load example .dwg file
3) Load .NET library
4) Run : "DST" command
5) Select object > Then ENTER
6) Force close happens (See picture attached)

![capture2](https://cloud.githubusercontent.com/assets/22008090/22591379/d3726540-ea46-11e6-9f49-1244c7d4b978.PNG)

[Analysis]
Caused : Index was outside the bounds of the array.
************** Exception Text **************
System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at AcadProjectExtractData.ExtractData.findSetFromAPoint() in D:\WEB DESIGN\GitHub\Projects\AcadProject\AcadProject\ExtractData.cs:line 224
   at AcadProject.Commands.SelectAllLines() in D:\WEB DESIGN\GitHub\Projects\AcadProject\AcadProject\MainClass.cs:line 148

`            fileName = "D:/extractInput.txt";
            mLineUtilObject.dump(extractData.getStringInput(), ed, fileName);
`

[Expected Result] Work fine without force close

**Comment by tuanvv90** [comment]
Remove DBText and narrow(actually it's a : Polyline) which link with DBText.
Force close won't happen. 

Conclusion : Skip this issue at present.
